$font = Inter
# BACKGROUND
background {
    monitor =
    #path = screenshot
    path =  ~/.local/share/CatalystHL/current-wallpaper   
    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
    disable_loading_bar = true
}

# GENERAL
general {
    hide_cursor = false
    grace = 0
    disable_loading_bar = true
    hide_cursor = true
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

# INPUT FIELD
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 0
    inner_color = rgba(255, 255, 255, 0.1)

    outer_color = rgba(216, 222, 233, 0.70)
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgba(200, 200, 200,0.5)
    fade_on_empty = false
    rounding = 40

    font_family = JetBrains Mono Extrabold
    placeholder_text = <i>Enter Password</i>
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -245
    halign = center
    valign = center
}

# DATE
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
  color = rgba(242, 243, 244, 0.6)
  font_size = 22
  #font_family = JetBrains Mono
  font_family = $font Medium
  position = 0, 290
  halign = center
  valign = center
}

# TIME
label {
  monitor = 
  text = cmd[update:1000] echo "$(date +"%-I:%M")"
  color = rgba(242, 243, 244, 0.5)
  font_size = 100
 # font_family = JetBrains Mono Extrabold
  font_family =$font Extrabold
  position = 0, 200
  halign = center
  valign = center
}


