##############################
### WINDOWS AND WORKSPACES ###
##############################

windowrule = suppress_event maximize, match:class .*

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Remove menu blur in chromium browser
windowrule = no_blur on, match:class ^$, match:title ^$

windowrule = float on, center on, match:class ^[xX]dg-desktop-portal-gtk$ 
windowrule = float on, center on, match:class ^xdg-desktop-portal-hyprland$

windowrule {
    name = signin_popup
    match:class = zen
    match:title = ^Sign in - Google Accounts.*
    float = on
    center = on
}

# image viewer
windowrule = float on, center on, match:class ^imv$

windowrule = opacity 0.8 override 0.8 override, match:class ^(nemo)$
windowrule = float on, center on, match:class ^(blueberry\.py)$

layerrule = blur on , match:namespace waybar
layerrule = ignore_alpha 0.0, match:namespace waybar

layerrule = ignore_alpha 0.0, match:namespace rofi
layerrule = blur on, match:namespace rofi
layerrule = animation popin 85%, match:namespace rofi

layerrule = animation slide right, match:namespace swaync-notification-window 
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.0, match:namespace swaync-control-center
layerrule = animation slide right, match:namespace swaync-control-center 

# slurp region selection
layerrule = animation fade, match:namespace selection
